# SPDX-FileCopyrightText: 2025 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

- type: parallax
  id: StellarBluespace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ST/Parallaxes/BG_Darkblue.png"
      slowness: 1

    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ST/Parallaxes/WISPS_Darkblue_2.png"
      slowness: 0.99

    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ST/Parallaxes/WISPS_Darkblue_3.png"
      slowness: 0.8

    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ST/Parallaxes/WISPS_Darkblue_2.png"
      slowness: 0.6
      scrolling: "0, 0.04"

    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ST/Parallaxes/WISPS_Darkblue.png"
      slowness: 0.3
      scrolling: "0, 0.1"

  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
  layersLQUseHQ: false

