// SPDX-FileCopyrightText: 2026 AftrLite
//
// SPDX-License-Identifier: LicenseRef-Wallening

using Content.Stellar.Shared.Weapons;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Stellar.Client.Weapons;

[GenerateTypedNameReferences]
public sealed partial class StellarAmmoControl : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly SpriteSystem _sprite;
    private readonly Entity<StellarGunTypesReloadableComponent> _ent;

    public StellarAmmoControl(Entity<StellarGunTypesReloadableComponent> ent)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entity.System<SpriteSystem>();
        _ent = ent;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_ent.Comp.Icon is { } icon)
            Icon.Texture = _sprite.Frame0(icon);

        if (_ent.Comp.AmmoCount is { } ammoCount && _ent.Comp.AmmoCapacity is { } ammoCapacity)
            Title.Text = Loc.GetString("stellar-ammo-ui-display", ("count", ammoCount), ("total", ammoCapacity));
    }
}
