// SPDX-FileCopyrightText: 2025 Janet Blackquill
//
// SPDX-License-Identifier: LicenseRef-Wallening

using Content.Stellar.Shared.ResourceBars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Stellar.Client.ResourceBars;

[GenerateTypedNameReferences]
public sealed partial class ResourceBarsUI : UIWidget
{
    private readonly Dictionary<ProtoId<ResourceBarPrototype>, ResourceBarControl> _resourceBars = new();

    public ResourceBarsUI()
    {
        RobustXamlLoader.Load(this);
    }

    public void Clear()
    {
        foreach (var position in Enum.GetValues<ResourceUIPosition>())
        {
            ContainerFor((ResourceUIPosition)position).RemoveAllChildren();
        }
        _resourceBars.Clear();
    }

    private BoxContainer ContainerFor(ResourceUIPosition position) =>
        position switch {
            ResourceUIPosition.Left => LeftContainer,
            ResourceUIPosition.Middle => MiddleContainer,
            ResourceUIPosition.Right => RightContainer,
            _ => throw new ArgumentOutOfRangeException(nameof(position), position, null)
        };

    public void Update(IPrototypeManager prototype, IReadOnlyDictionary<ProtoId<ResourceBarPrototype>, ResourceBarState> bars)
    {
        foreach (var (key, child) in _resourceBars)
        {
            if (bars.ContainsKey(key))
                continue;

            child.Parent?.Children.Remove(child);
            _resourceBars.Remove(key);
        }

        foreach (var (barID, data) in bars)
        {
            if (_resourceBars.TryGetValue(barID, out var existingBar))
            {
                existingBar.Update(data);
                continue;
            }

            var bar = prototype.Index(barID);

            var container = ContainerFor(bar.Location);
            container.AddChild(_resourceBars[barID] = new ResourceBarControl(bar, data));
        }
    }
}
