# SPDX-FileCopyrightText: 2025 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

### SCIENTIST
- type: job
  id: StellarJobScienceScientist
  name: stellar-job-name-scientist
  description: stellar-job-description-scientist
  setPreference: true
  playTimeTracker: StellarTimeTrackerScienceScientist
  # requirements:
  #   - !type:DepartmentTimeRequirement
  #     department: Civilian
  #     time: 0.5h
  startingGear: StellarGearScienceScientist
  icon: StellarJobIconScienceScientist
  supervisors: job-supervisors-hop
  access:
  - Service

- type: job
  id: StellarJobScienceAnalyst
  name: stellar-job-name-analyst
  description: stellar-job-description-analyst
  setPreference: true
  playTimeTracker: StellarTimeTrackerScienceAnalyst
  # requirements:
  #   - !type:DepartmentTimeRequirement
  #     department: Civilian
  #     time: 0.5h
  startingGear: StellarGearScienceAnalyst
  icon: StellarJobIconScienceAnalyst
  supervisors: job-supervisors-hop
  access:
  - Service


- type: playTimeTracker
  id: StellarTimeTrackerScienceScientist

- type: playTimeTracker
  id: StellarTimeTrackerScienceAnalyst
