// SPDX-FileCopyrightText: 2026 AftrLite
//
// SPDX-License-Identifier: LicenseRef-Wallening

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Stellar.Client.Crafting;

[GenerateTypedNameReferences]
public sealed partial class StellarRecipeEntityEmbed : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public Entity<SpriteComponent>? Sprite => View.Entity == null || View.Sprite == null
        ? null
        : (View.Entity.Value, View.Sprite);

    public Vector2 Scale
    {
        get => View.Scale;
        set => View.Scale = value;
    }

    public StellarRecipeEntityEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.entity");
    }

    public StellarRecipeEntityEmbed(string proto) : this()
    {
        var ent = _entityManager.SpawnEntity(proto, MapCoordinates.Nullspace);
        View.SetEntity(ent);
    }

    public StellarRecipeEntityEmbed(string proto, out EntityUid localEnt) : this()
    {
        var ent = _entityManager.SpawnEntity(proto, MapCoordinates.Nullspace);
        View.SetEntity(ent);

        localEnt = ent;
    }

    protected override void Deparented()
    {
        base.Deparented();

        if (Sprite is not null)
            _entityManager.DeleteEntity(Sprite);
    }
}
