// SPDX-FileCopyrightText: 2026 AftrLite
//
// SPDX-License-Identifier: LicenseRef-Wallening

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;


namespace Content.Stellar.Client.Crafting;

[GenerateTypedNameReferences]
public sealed partial class StellarCraftingMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public EntityUid Entity;

    public StellarCraftingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // _spriteSystem = _entityManager.System<SpriteSystem>();
        // ConfirmButton.OnPressed += _ => Close();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        this.SetInfoFromEntity(_entityManager, Entity);
    }
}
