// SPDX-FileCopyrightText: 2026 AftrLite
//
// SPDX-License-Identifier: LicenseRef-Wallening

using System.Linq;
using System.Numerics;
using Content.Client.Examine;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Stellar.Shared.Crafting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;


namespace Content.Stellar.Client.Crafting;

[GenerateTypedNameReferences]
public sealed partial class StellarCraftingMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    private ProtoId<StellarCraftingRecipePrototype>? _selectedRecipeProtoId;
    private EntityUid _uid;

    private readonly ButtonGroup _recipeButtonGroup;
    private readonly ExamineSystem _examine;
    private readonly SpriteSystem _sprite;

    public Action<ProtoId<StellarCraftingRecipePrototype>>? OnRecipeButtonPressed;
    public Action? OnCancelButtonPressed;

    public StellarCraftingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _examine = _entMan.System<ExamineSystem>();
        _sprite = _entMan.System<SpriteSystem>();
        _recipeButtonGroup = new ButtonGroup();

        CancelButton.OnPressed += _ => CancelRecipe();
    }

    public void SetEntity(EntityUid uid)
    {
        _uid = uid;
        var comp = _entMan.GetComponent<StellarCraftingBenchComponent>(uid);

        if (comp.IngredientReqs.Count > 0
            && comp.SelectedRecipe != null
            && _proto.TryIndex(comp.SelectedRecipe, out var recipe))
            ExistingRecipe(comp, recipe);

        this.SetInfoFromEntity(_entMan, _uid);
        LoadRecipes(uid, comp);
    }

    public void UpdateRecipe(NetEntity owner)
    {
        var uid = _entMan.GetEntity(owner);
        var comp = _entMan.GetComponent<StellarCraftingBenchComponent>(uid);

        if (comp.SelectedRecipe == null || !_proto.TryIndex(comp.SelectedRecipe, out var recipe))
            return;

        SetIngredients(recipe.IngredientList, comp.IngredientReqs);
    }

    private void ExistingRecipe(StellarCraftingBenchComponent comp, StellarCraftingRecipePrototype proto)
    {
        MasterTabContainer.CurrentTab = 1;

        SetHeader(proto.Output);
        SetIngredients(proto.IngredientList, comp.IngredientReqs);
    }

    private void SelectRecipe(Button button, StellarCraftingRecipePrototype proto)
    {
        button.Pressed = false;
        MasterTabContainer.CurrentTab = 1;
        OnRecipeButtonPressed?.Invoke(proto.ID);

        SetHeader(proto.Output);
        SetIngredients(proto.IngredientList, null);
    }

    private void CancelRecipe()
    {
        _selectedRecipeProtoId = null;
        MasterTabContainer.CurrentTab = 0;
        OnCancelButtonPressed?.Invoke();
    }

    private void LoadRecipes(EntityUid uid, StellarCraftingBenchComponent comp)
    {
        RecipeContainer.RemoveAllChildren();
        foreach (var recipe in comp.AvailableRecipes)
        {
            if (!_proto.TryIndex(recipe, out var proto))
                continue;

            var ingredient = _proto.Index<EntityPrototype>(proto.Output);

            var amountMsg = new FormattedMessage();
            amountMsg.AddMarkupOrThrow(Loc.GetString("stellar-crafting-display-name", ("name", ingredient.Name)));
            amountMsg.Pop();

            var amountLabel = new RichTextLabel();
            amountLabel.SetMessage(amountMsg);

            var boxCont = new BoxContainer();
            var view = new StellarRecipeEntityEmbed(proto.Output)
            {
                Scale =  new Vector2(2f, 2f),
            };

            var button = new Button
            {
                HorizontalExpand = false,
                StyleClasses = { StyleClass.ButtonSquare },
                Group = _recipeButtonGroup,
                Pressed = proto.ID == _selectedRecipeProtoId,
                ToolTip = Loc.GetString(ingredient.Description),
            };

            button.OnPressed += _ => SelectRecipe(button, proto);

            button.AddChild(boxCont);
            boxCont.AddChild(view);
            boxCont.AddChild(amountLabel);
            RecipeContainer.AddChild(button);
        }
    }

    private void SetHeader(EntProtoId ent)
    {
        var entity = _proto.Index<EntityPrototype>(ent);
        var view = new StellarRecipeEntityEmbed(ent)
        {
            Scale = new Vector2(3f, 3f),
        };

        IconContainer.RemoveAllChildren();
        IconContainer.AddChild(view);
        ResultName.Text = Loc.GetString("stellar-crafting-display-name", ("name", entity.Name));
        ResultDescription.Text = Loc.GetString("stellar-crafting-display-description", ("name", entity.Description));
    }

    private void SetIngredients(IReadOnlyDictionary<string, int> ingredients, IReadOnlyDictionary<string, int>? remaining)
    {
        IngredientsGrid.RemoveAllChildren();
        foreach (var (product, amount) in ingredients)
        {
            var totalAmount = amount;
            if (remaining != null && remaining.TryGetValue(product, out var value))
                totalAmount = value;

            var amountMsg = new FormattedMessage();
            amountMsg.AddMarkupOrThrow(Loc.GetString("stellar-crafting-display-amount", ("amount", totalAmount)));
            amountMsg.Pop();

            var amountLabel = new RichTextLabel();
            amountLabel.SetMessage(amountMsg);

            var boxCont = new BoxContainer();
            var view = new StellarRecipeEntityEmbed(product, out var ent)
            {
                Scale = new Vector2(2f, 2f),
            };
            var button = new Button();

            if (remaining != null && !remaining.ContainsKey(product))
            {
                if (view.Sprite != null)
                    _sprite.SetColor(view.Sprite.Value.Owner, Color.LightGreen);
                view.Modulate = Color.LightGreen;
                button.Modulate = Color.LightGreen;
                button.Disabled = true;
            }
            else
            {
                button.OnPressed += _ => _examine.DoExamine(ent);
                boxCont.AddChild(amountLabel);
            }

            boxCont.HorizontalExpand = true;
            boxCont.HorizontalAlignment = HAlignment.Center;
            boxCont.AddChild(view);
            button.AddChild(boxCont);
            IngredientsGrid.AddChild(button);
        }
    }
}
