# SPDX-FileCopyrightText: 2026 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

- type: entity
  abstract: true
  parent: [StellarClothingOuterBase]
  id: StellarHardsuitBase
  categories: [ HideSpawnMenu ]
  components:
  # SlotBlocker blocked until UI change | AftrLite says: What?
  #  - type: SlotBlock
  #    slots: [innerclothing, feet]
#  - type: Geiger
#    attachedToSuit: true | Commented out for now, Geiger sounds are atrocious.
  - type: AllowSuitStorage
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000
  - type: TemperatureProtection
    heatingCoefficient: 0.01
    coolingCoefficient: 0.01
  - type: ClothingSpeedModifier
    walkModifier: 0.8
    sprintModifier: 0.8
  - type: HeldSpeedModifier
  - type: Item
    size: Ginormous
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.9
        Slash: 0.9
        Piercing: 0.9
        Heat: 0.9
        Radiation: 0.9
  - type: ToggleableClothing
    slot: head
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
  - type: GroupExamine
  - type: Tag
    tags:
    - Hardsuit
    - WhitelistChameleon
  - type: ProtectedFromStepTriggers
    slots: WITHOUT_POCKET
  - type: DamageOnInteractProtection
    damageProtection:
      flatReductions:
        Heat: 10 # the average lightbulb only does around four damage!
    slots: OUTERCLOTHING
  - type: HideLayerClothing
    slots: # THE CHARACTER IS WEARING A HARDSUIT. WE DO NOT NEED TO SEE THE CHARACTER. HIDE EVERYTHING THAT ISN'T ON THE HEAD.
    - Tail
    - UndergarmentTop
    - UndergarmentBottom
    - Chest
    - RArm
    - LArm
    - RHand
    - LHand
    - RLeg
    - LLeg
    - RFoot
    - LFoot

- type: entity
  abstract: true
  id: StellarHardsuitHelmetBase
  categories: [ HideSpawnMenu ]
  components:
  # SlotBlocker blocked until UI change
  #  - type: SlotBlock
  #    slots: [ears, eyes, mask]
  - type: BreathMask
  - type: Sprite
    state: icon # default state used by most inheritors
  - type: Clickable
  - type: InteractionOutline
  - type: Clothing
    #Apparently the hardsuit helmet equip sound is from a walking mech?
    equipSound: /Audio/Mecha/mechmove03.ogg
    unequipSound: /Audio/Mecha/mechmove03.ogg
    quickEquip: false
    slots: [ HEAD ]
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000
  - type: TemperatureProtection
    heatingCoefficient: 0.1
    coolingCoefficient: 0.1
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.90
        Slash: 0.90
        Piercing: 0.95
        Heat: 0.90
        Radiation: 0.25
  - type: GroupExamine
  - type: IngestionBlocker
  - type: Tag
    tags:
    - WhitelistChameleon
  - type: IdentityBlocker
  - type: HideLayerClothing
    slots:
    - Hair
    - Snout
    - HeadTop
    - HeadSide
    - FacialHair
