using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ST.ResourceBars.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ResourceBarsGui : UIWidget
{
    public ResourceBarsGui()
    {
        RobustXamlLoader.Load(this);

        // var resourceBarUIController = UserInterfaceManager.GetUIController<ResourceBarsUIController>();
        // resourceBarUIController.RegisterResourceBarContainer(ResourceBar);

        // LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }
}
