- type: entity
  id: StellarCookerBase
  parent: BaseStorageItem
  abstract: true
  components:
  - type: Sprite
    noRot: true
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        base:
          True: { state: opened }
          False: { state: closed }
      enum.CP14CookingVisuals.Cooking:
        cook:
          True: { visible: true }
          False: { visible: false }
      enum.CP14CookingVisuals.Burning:
        burn:
          True: { visible: true }
          False: { visible: false }
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: Storage
    maxItemSize: Normal
    grid:
    - 0,0,3,3
    whitelist:
      components:
        - Food
        - Edible
    earlyIgnorelist:
      components:
        - CP14FoodHolder
        - FoodSequenceStartPoint
  - type: CP14FoodCooker
    cookMethod: Temperature
    containerId: storagebase
  - type: DoAfter
  - type: AmbientSound
    enabled: false
    volume: 5
    range: 5
